### ISSUE TITLE
Travis-CI UI Screenshots are out of date.

### ISSUE THREAD

**Issue by iteles** [nelsonic/learn-travis#1]
Screenshot of the latest screen from Travis, requesting permission to access Github attached below (although this is with my username which might get a bit confusing...!)

![travis-ci-permission-to-access-github-fullscreen-with-text](https://cloud.githubusercontent.com/assets/4185328/5859970/3b6fac6a-a256-11e4-9e9a-6b9a38099873.jpg)

**Comment by nelsonic** [comment]
![awesome-sauce](https://cloud.githubusercontent.com/assets/194400/5874158/2140f04c-a2f6-11e4-9b37-e7c38def528a.png)
